apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: adservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/adservice:v0.1.2
        ports:
          - containerPort: 8080
            name: h2c
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: cartservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/google-samples/microservices-demo/cartservice:v0.1.2
            args: ["-p", "$(PORT)"]
            ports:
              - containerPort: 7070
                name: h2c
            env:
              - name: REDIS_ADDR
                value: "redis-cart:6379"
              - name: LISTEN_ADDR
                value: "0.0.0.0"
            resources:
              requests:
                cpu: 200m
                memory: 64Mi
              limits:
                cpu: 300m
                memory: 128Mi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: checkoutservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.1.2
        ports:
          - containerPort: 8080
            name: h2c
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.default.svc.cluster.local:80"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.default.svc.cluster.local:80"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.default.svc.cluster.local:80"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.default.svc.cluster.local:80"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.default.svc.cluster.local:80"
          - name: CART_SERVICE_ADDR
            value: "cartservice.default.svc.cluster.local:80"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: currencyservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
        spec:
          container:
            image: gcr.io/google-samples/microservices-demo/currencyservice:v0.1.2
            ports:
              - containerPort: 7000
                name: h2c
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: emailservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/google-samples/microservices-demo/emailservice:v0.1.2
            ports:
              - containerPort: 8080
                name: h2c
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/onlineboutique/frontend:v0.1.2
            env:
              - name: PRODUCT_CATALOG_SERVICE_ADDR
                value: "productcatalogservice.default.svc.cluster.local:80"
              - name: CURRENCY_SERVICE_ADDR
                value: "currencyservice.default.svc.cluster.local:80"
              - name: CART_SERVICE_ADDR
                value: "cartservice.default.svc.cluster.local:80"
              - name: RECOMMENDATION_SERVICE_ADDR
                value: "recommendationservice.default.svc.cluster.local:80"
              - name: SHIPPING_SERVICE_ADDR
                value: "shippingservice.default.svc.cluster.local:80"
              - name: CHECKOUT_SERVICE_ADDR
                value: "checkoutservice.default.svc.cluster.local:80"
              - name: AD_SERVICE_ADDR
                value: "adservice.default.svc.cluster.local:80"
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: paymentservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/google-samples/microservices-demo/paymentservice:v0.1.2
            ports:
              - containerPort: 8080
                name: h2c
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: productcatalogservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/onlineboutique/productcatalogservice:v0.1.2
            ports:
              - containerPort: 3550
                name: h2c
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: recommendationservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.1.2
            ports:
              - containerPort: 8080
                name: h2c
            env:
              - name: PRODUCT_CATALOG_SERVICE_ADDR
                value: "productcatalogservice.default.svc.cluster.local:80"
            resources:
              requests:
                cpu: 100m
                memory: 220Mi
              limits:
                cpu: 200m
                memory: 450Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: shippingservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/google-samples/microservices-demo/shippingservice:v0.1.2
            ports:
              - containerPort: 50051
                name: h2c
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
