apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: emailservice
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/emailservice:v0.1.2
        ports:
          - containerPort: 8080
            name: h2c
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi